# Use the official Node.js 20-slim base image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Install serve to serve the build
RUN npm install -g serve

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Expose the port the app runs on  (only for documentation, does not actually publish the port)
# this is for the port on the container, not the host/server
EXPOSE 8800

# Start the app using serve
CMD ["serve", "-s", "dist", "-l", "8800"]
